services:
  client-gateway:
    build: ../client-gateway
    ports:
      - 3018:3018
    volumes:
      - ../client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ../client-gateway/.env
